[package]
name = "infinit-shooter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy="0.8"
rand="0.8.5"
bevy-inspector-egui = "0.13.0"

[workspace]
resolver="2"
